name: Test Reusable Workflow Call

on:
  workflow_dispatch:

jobs:
  call-test:
    name: Test Call
    runs-on: ubuntu-latest
    steps:
      - name: Simple step
        run: echo "Testing workflow call"

  call-reusable:
    name: Call Reusable
    needs: call-test
    uses: mnelson3/nelson-grey/.github/workflows/ios-build.yml@main
    with:
      project_name: "test"
      release_type: "build_only"
      ruby_version: "3.2"
      bundler_version: "2.4.22"
      fastlane_version: "2.230.0"
    secrets:
      app_store_connect_key_id: test
      app_store_connect_issuer_id: test
      app_store_connect_key: test
      match_password: test
      match_git_url: test
      match_git_branch: test
