name: Test Minimal Reusable on Push

on:
  push:
    branches:
      - test-branch

jobs:
  call-minimal:
    uses: mnelson3/nelson-grey/.github/workflows/minimal-reusable.yml@main
    with:
      test_input: "hello"
