name: Test Master Pipeline Trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        required: true
        type: choice
        options:
          - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Test successful - action=${{ github.event.inputs.action }}"
