
name: modulo
version: 0.0.1+1
description: A modulo based puzzle game with leaderboard.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.7.0
  firebase_core: ^2.13.0
  audioplayers: ^6.4.0
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
