// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRHVb9cigFuu2dxxfL3_0MaeFvypm-3I',
    appId: '1:784677197785:web:17eec81cc847f1af61abc8',
    messagingSenderId: '784677197785',
    projectId: 'modulo-squares-dev',
    authDomain: 'modulo-squares-dev.firebaseapp.com',
    storageBucket: 'modulo-squares-dev.firebasestorage.app',
    measurementId: 'G-RPFZ8V8Q8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq66LnI1c7jSSRgs7hbdz-9lMkA92MfqA',
    appId: '1:784677197785:android:2bf6f5985343359661abc8',
    messagingSenderId: '784677197785',
    projectId: 'modulo-squares-dev',
    storageBucket: 'modulo-squares-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmHtmyARvoj5FjgZgIkrj1cs8RHo3nQg',
    appId: '1:784677197785:ios:fa6f0aac2aa0b54961abc8',
    messagingSenderId: '784677197785',
    projectId: 'modulo-squares-dev',
    storageBucket: 'modulo-squares-dev.firebasestorage.app',
    iosClientId:
        '784677197785-1bvq4scskbet0lndg67karbgph2fhrsk.apps.googleusercontent.com',
    iosBundleId: 'com.modulosquares.app.ios',
  );
}
