// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXho7IXqU_bt3jS3WvP_VsIYjJtWrs5Dg',
    appId: '1:239807122511:web:89c06cdf09b0845900ee3a',
    messagingSenderId: '1038873713695',
    projectId: 'modulo-squares',
    authDomain: 'modulo-squares.firebaseapp.com',
    storageBucket: 'modulo-squares.firebasestorage.app',
    measurementId: 'G-KPX3GHW9VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXho7IXqU_bt3jS3WvP_VsIYjJtWrs5Dg',
    appId: '1:1038873713695:android:8cc29f252bb8b1e6bcc92a',
    messagingSenderId: '1038873713695',
    projectId: 'modulo-squares',
    storageBucket: 'modulo-squares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXho7IXqU_bt3jS3WvP_VsIYjJtWrs5Dg',
    appId: '1:1038873713695:ios:fd144b35448ed1e6bcc92a',
    messagingSenderId: '1038873713695',
    projectId: 'modulo-squares',
    storageBucket: 'modulo-squares.firebasestorage.app',
    iosBundleId: 'com.nelsongrey.modulosquares.app.ios',
  );
}
