name: 'Setup Flutter'
description: 'Setup Flutter SDK with caching'

inputs:
  flutter-version:
    description: 'Flutter version to install'
    required: true
    default: '3.35.7'

runs:
  using: 'composite'
  steps:
    - name: 🦋 Setup Flutter
      uses: subosito/flutter-action@v2.21.0
      with:
        flutter-version: ${{ inputs.flutter-version }}
        architecture: arm64
        cache: true

    - name: 📦 Install Flutter Dependencies
      run: flutter pub get
      shell: bash
      working-directory: packages/mobile