// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBPlwtutn6Eu3WC2nMKQoQ95yxjYPeSY',
    appId: '1:253948321735:web:0f7df38ef2e47fe89ec3e2',
    messagingSenderId: '253948321735',
    projectId: 'modulo-squares-prod',
    authDomain: 'modulo-squares-prod.firebaseapp.com',
    storageBucket: 'modulo-squares-prod.firebasestorage.app',
    measurementId: 'G-FY0QLHWYJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKxqXgalzbqf9kFBIrAsq2gyFHHSZXF0',
    appId: '1:253948321735:android:f58a8b194384a9379ec3e2',
    messagingSenderId: '253948321735',
    projectId: 'modulo-squares-prod',
    storageBucket: 'modulo-squares-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdIM2EJ7bsJgX8xB8yDDtqU9DooXF0w4',
    appId: '1:253948321735:ios:a56e8f3551eabcd79ec3e2',
    messagingSenderId: '253948321735',
    projectId: 'modulo-squares-prod',
    storageBucket: 'modulo-squares-prod.firebasestorage.app',
    iosClientId: '253948321735-hlmtsh9v7v766sac03nt68h9ftk7vsc5.apps.googleusercontent.com',
    iosBundleId: 'com.modulosquares.app.ios',
  );
}
