#!/bin/bash
# 🌍 Environment & Secret Management System

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; PURPLE='\033[0;35m'; NC='\033[0m'

# Helper functions
log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_header() { echo -e "${PURPLE}🌍 $1${NC}"; echo -e "${PURPLE}$(printf '%.0s=' {1..50})${NC}"; }

# CRITICAL: Bash 3.2 compatibility - NO associative arrays
# Use variable naming convention: ENV_CONFIGS_<environment>
ENV_CONFIGS_development="modulo-squares-dev"
ENV_CONFIGS_staging="modulo-squares-staging"
ENV_CONFIGS_production="modulo-squares-prod"

# Validate environment
validate_environment() {
    case "$ENVIRONMENT" in
        development|staging|production) return 0 ;;
        *) log_error "Invalid environment: $ENVIRONMENT"; exit 1 ;;
    esac
}

# Get Firebase project (Bash 3.2 compatible)
get_firebase_project() {
    eval "echo \$ENV_CONFIGS_$ENVIRONMENT"
}

# Generate secure secrets
generate_secret() { openssl rand -hex "${1:-32}"; }
generate_password() { openssl rand -base64 "${1:-24}" | tr -d "=+/" | cut -c1-"${1:-24}"; }

# Environment file management
manage_env_files() {
    log_header "Environment File Management"

    cd "$PROJECT_ROOT"

    # Create environment-specific files
    local env_file=".env.$ENVIRONMENT"

    if [ -f "$env_file" ]; then
        log_info "Environment file already exists: $env_file"
        return
    fi

    log_info "Creating environment file: $env_file"

    # Get Firebase project
    local firebase_project=$(get_firebase_project)

    # Create basic environment file
    cat > "$env_file" << EOF
# Modulo Squares - $ENVIRONMENT Environment
# Generated by automation system

# Firebase Configuration
FIREBASE_PROJECT_ID=$firebase_project

# Environment
ENVIRONMENT=$ENVIRONMENT

# Add environment-specific variables here
EOF

    log_success "Environment file created: $env_file"
}

# GitHub Secrets management
manage_github_secrets() {
    log_header "GitHub Secrets Management"

    # Check GitHub CLI authentication
    if ! command -v gh > /dev/null 2>&1; then
        log_error "GitHub CLI not installed"
        exit 1
    fi

    if ! gh auth status > /dev/null 2>&1; then
        log_error "GitHub CLI not authenticated. Run: gh auth login"
        exit 1
    fi

    cd "$PROJECT_ROOT"

    # Load automation config
    if [ -f ".env.automation.$ENVIRONMENT" ]; then
        source ".env.automation.$ENVIRONMENT"
    fi

    # Repository information
    local repo="${GITHUB_REPO:-mnelson3/modulo-squares}"

    log_info "Syncing secrets for repository: $repo"

    # Common secrets that apply to all environments
    local common_secrets=(
        "FIREBASE_SERVICE_ACCOUNT_KEY"
        "GITHUB_TOKEN"
    )

    # Environment-specific secrets
    local env_secrets=()

    case "$ENVIRONMENT" in
        "development")
            env_secrets=(
                "FIREBASE_CONFIG_DEV"
            )
            ;;
        "staging")
            env_secrets=(
                "FIREBASE_CONFIG_STAGING"
            )
            ;;
        "production")
            env_secrets=(
                "FIREBASE_CONFIG_PROD"
                "IOS_DISTRIBUTION_CERTIFICATE_BASE64"
                "IOS_PROVISIONING_PROFILE_BASE64"
                "IOS_CERTIFICATE_PASSWORD"
                "ANDROID_KEYSTORE_BASE64"
                "ANDROID_KEYSTORE_PASSWORD"
            )
            ;;
    esac

    # Sync common secrets
    for secret in "${common_secrets[@]}"; do
        local value=$(eval "echo \$$secret")
        if [ -n "$value" ]; then
            log_info "Setting secret: $secret"
            echo "$value" | gh secret set "$secret" --repo "$repo"
        else
            log_warning "Secret not found in config: $secret"
        fi
    done

    # Sync environment-specific secrets
    for secret in "${env_secrets[@]}"; do
        local value=$(eval "echo \$$secret")
        if [ -n "$value" ]; then
            log_info "Setting secret: $secret"
            echo "$value" | gh secret set "$secret" --repo "$repo"
        else
            log_warning "Secret not found in config: $secret"
        fi
    done

    log_success "Secrets synchronized for $ENVIRONMENT environment"
}

# Show status
show_status() {
    log_header "Environment Status - $ENVIRONMENT"

    cd "$PROJECT_ROOT"

    # Check environment file
    local env_file=".env.$ENVIRONMENT"
    if [ -f "$env_file" ]; then
        log_success "Environment file exists: $env_file"
    else
        log_warning "Environment file missing: $env_file"
    fi

    # Check Firebase project
    local firebase_project=$(get_firebase_project)
    if [ -n "$firebase_project" ]; then
        log_success "Firebase project configured: $firebase_project"
    else
        log_warning "Firebase project not configured for $ENVIRONMENT"
    fi

    # Check GitHub CLI
    if command -v gh > /dev/null 2>&1; then
        if gh auth status > /dev/null 2>&1; then
            log_success "GitHub CLI authenticated"
        else
            log_warning "GitHub CLI not authenticated"
        fi
    else
        log_warning "GitHub CLI not installed"
    fi

    # Check Firebase CLI
    if command -v firebase > /dev/null 2>&1; then
        log_success "Firebase CLI installed"
    else
        log_warning "Firebase CLI not installed"
    fi
}

# Main function
main() {
    ENVIRONMENT="${1:-development}"
    ACTION="${2:-status}"

    validate_environment

    case "$ACTION" in
        "setup") manage_env_files ;;
        "sync-secrets") manage_github_secrets ;;
        "status") show_status ;;
        *) log_error "Unknown action: $ACTION"; exit 1 ;;
    esac
}

main "$@"