name: Test Minimal Reusable

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  call-minimal:
    uses: mnelson3/nelson-grey/.github/workflows/minimal-reusable.yml@80292d003fa84491b4701a3b97d317cdb3b318ab
    with:
      test_input: "hello"
